# Generated by Django 5.2.2 on 2025-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_picture_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town'),
        ),
    ]
